"""Typed models for defense synthesis and validation."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class IsolatedSegment:
    """Minimal attack payload extracted from a trace."""

    attack_payload: str
    target_response: str
    persona_name: str
    persona_tactic: str
    trace_id: str
    score: float
    target_system_prompt: str = ""


@dataclass
class VulnerabilityClassification:
    """Result of classifying the vulnerability."""

    category: str
    owasp_ref: str
    mitre_atlas_ref: str
    severity: str
    attack_vector: str


@dataclass
class GuardrailProposal:
    """A proposed system-prompt clause generated by the Defense Architect."""

    clause: str
    rationale: str
    classification: VulnerabilityClassification


@dataclass
class BenignValidationCheck:
    """Result of one benign prompt replay against a patched target."""

    case_id: str
    prompt: str
    response: str
    passed: bool
    matched_keywords: list[str] = field(default_factory=list)
    missing_keywords: list[str] = field(default_factory=list)
    refusal_detected: bool = False
    failure_reason: str = ""


@dataclass
class ReplayCaseResult:
    """Result of one sealed replay case in the defense validation suite."""

    case_id: str
    kind: str
    prompt: str
    response: str
    passed: bool
    rubric_name: str = "authorization_bypass"
    judge_score: float | None = None
    matched_keywords: list[str] = field(default_factory=list)
    missing_keywords: list[str] = field(default_factory=list)
    refusal_detected: bool = False
    failure_reason: str = ""


@dataclass
class ValidationResult:
    """Result of re-running the attack and benign pack against the patch."""

    passed: bool
    replay_response: str
    judge_score: float
    exploit_replay_passed: bool | None = None
    benign_passed: bool | None = None
    benign_checks: list[BenignValidationCheck] = field(default_factory=list)
    replay_cases: list[ReplayCaseResult] = field(default_factory=list)
    replay_suite_id: str = "default-defense-replay-v1"
    validation_mode: str = "live"
    failure_reason: str = ""

    def __post_init__(self) -> None:
        if self.exploit_replay_passed is None:
            self.exploit_replay_passed = self.passed
        if self.benign_passed is None:
            self.benign_passed = self.passed


@dataclass
class DeploymentRecord:
    """Immutable record written to MEMORY.md after successful deploy."""

    trace_id: str
    guardrail_clause: str
    classification: VulnerabilityClassification
    validation: ValidationResult
    target_model: str
    target_system_prompt_hash: str
    metadata: dict[str, Any] = field(default_factory=dict)


__all__ = [
    "BenignValidationCheck",
    "DeploymentRecord",
    "GuardrailProposal",
    "IsolatedSegment",
    "ReplayCaseResult",
    "ValidationResult",
    "VulnerabilityClassification",
]
