"""Read/write interface for the append-only RedThread memory index."""

from __future__ import annotations

import json
import logging
from collections.abc import Iterable
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from redthread.config.settings import RedThreadSettings
from redthread.core.defense_synthesis import (
    BenignValidationCheck,
    DeploymentRecord,
    ValidationResult,
    VulnerabilityClassification,
)

logger = logging.getLogger(__name__)

_MEMORY_FILENAME = "MEMORY.md"
_DEPLOYMENTS_FILENAME = "deployments.jsonl"
_HEADER = (
    "# RedThread Threat Knowledge Base\n\n"
    "This file is auto-generated by the Defense Synthesis Engine.\n"
    "Each entry represents a confirmed jailbreak and its validated guardrail fix.\n\n"
    "---\n\n"
)
_ENTRY_TEMPLATE = """\
## {timestamp} | {category} | {severity}
**Trace:** `{trace_id}`
**Scope:** model=`{model}` | prompt_hash=`{prompt_hash}`
**Attack vector:** {attack_vector}

> **Guardrail clause:** {clause}

**OWASP ref:** {owasp_ref} | **MITRE ATLAS:** {mitre_ref}
**Validated:** {validated_str}

---

"""


class MemoryIndex:
    """Access append-only markdown and JSONL deployment records."""

    def __init__(self, settings: RedThreadSettings) -> None:
        self._path: Path = settings.memory_dir / _MEMORY_FILENAME
        self._deployments_path: Path = settings.memory_dir / _DEPLOYMENTS_FILENAME
        self._ensure_files()

    def append(self, record: DeploymentRecord) -> bool:
        """Append a deployment record unless its trace ID already exists."""
        if self._is_duplicate(record.trace_id):
            logger.debug("MemoryIndex: duplicate trace_id=%s — skipping.", record.trace_id)
            return False
        with self._path.open("a", encoding="utf-8") as handle:
            handle.write(self._format_entry(record))
        with self._deployments_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(asdict(record)) + "\n")
        logger.info("📚 MemoryIndex updated | trace=%s | category=%s", record.trace_id, record.classification.category)
        return True

    def append_records(self, records: Iterable[DeploymentRecord]) -> list[str]:
        """Append a bounded batch and return the trace IDs written this time."""
        written: list[str] = []
        for record in records:
            if self.append(record):
                written.append(record.trace_id)
        return written

    def all_entries_raw(self) -> str:
        return self._path.read_text(encoding="utf-8") if self._path.exists() else ""

    def known_trace_ids(self) -> list[str]:
        deployments = self.iter_deployments()
        if deployments:
            return [record.trace_id for record in deployments]
        return [
            line.replace("**Trace:**", "").strip().strip("`")
            for line in self.all_entries_raw().splitlines()
            if line.startswith("**Trace:**")
        ]

    def iter_deployments(self) -> list[DeploymentRecord]:
        if not self._deployments_path.exists():
            return []
        return [self._deserialize(line) for line in self._deployments_path.read_text(encoding="utf-8").splitlines() if line.strip()]

    def deployments_by_trace_ids(self, trace_ids: Iterable[str]) -> list[DeploymentRecord]:
        wanted = set(trace_ids)
        if not wanted:
            return []
        return [record for record in self.iter_deployments() if record.trace_id in wanted]

    def load_scoped_guardrails(self, target_model: str, prompt_hash: str) -> list[str]:
        clauses: list[str] = []
        for block in self.all_entries_raw().split("---\n\n"):
            if "✅ YES" not in block or f"model=`{target_model}` | prompt_hash=`{prompt_hash}`" not in block:
                continue
            for line in block.splitlines():
                if line.startswith("> **Guardrail clause:**"):
                    clauses.append(line.replace("> **Guardrail clause:**", "").strip())
                    break
        return clauses

    def _ensure_files(self) -> None:
        if not self._path.exists():
            self._path.parent.mkdir(parents=True, exist_ok=True)
            self._path.write_text(_HEADER, encoding="utf-8")
        if not self._deployments_path.exists():
            self._deployments_path.touch()

    def _deserialize(self, line: str) -> DeploymentRecord:
        payload = json.loads(line)
        validation_payload = payload["validation"]
        benign_checks = [
            BenignValidationCheck(**check)
            for check in validation_payload.get("benign_checks", [])
        ]
        return DeploymentRecord(
            trace_id=payload["trace_id"],
            guardrail_clause=payload["guardrail_clause"],
            classification=VulnerabilityClassification(**payload["classification"]),
            validation=ValidationResult(
                **{
                    **validation_payload,
                    "benign_checks": benign_checks,
                }
            ),
            target_model=payload["target_model"],
            target_system_prompt_hash=payload["target_system_prompt_hash"],
            metadata=payload.get("metadata", {}),
        )

    def _is_duplicate(self, trace_id: str) -> bool:
        return trace_id in self.known_trace_ids()

    def _format_entry(self, record: DeploymentRecord) -> str:
        validation = record.validation
        status = "✅ YES" if validation.passed else "❌ NO"
        benign_suffix = ""
        if validation.benign_checks:
            passed = sum(1 for check in validation.benign_checks if check.passed)
            benign_suffix = f" | benign pack: {passed}/{len(validation.benign_checks)}"
        validated_str = f"{status} (residual score: {validation.judge_score:.2f}{benign_suffix})"
        return _ENTRY_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            category=record.classification.category,
            severity=record.classification.severity,
            trace_id=record.trace_id,
            model=record.target_model,
            prompt_hash=record.target_system_prompt_hash,
            attack_vector=record.classification.attack_vector or "N/A",
            clause=record.guardrail_clause,
            owasp_ref=record.classification.owasp_ref,
            mitre_ref=record.classification.mitre_atlas_ref,
            validated_str=validated_str,
        )
