"""Memory Index — manages the MEMORY.md markdown index file.

`MEMORY.md` is the persistent threat-knowledge store written to
`settings.memory_dir / "MEMORY.md"`. Each entry records a confirmed
jailbreak, its guardrail fix, and whether the fix was validated.

Format (per entry)::

    ## [TIMESTAMP] | [CATEGORY] | [SEVERITY]
    **Trace:** `<trace_id>`
    **Attack vector:** <one-line description>
    **Guardrail clause:** > <clause text>
    **OWASP ref:** <LLM0X> | **MITRE ATLAS:** <AML.TXXXX>
    **Validated:** ✅ YES (residual score: 1.2)

The index file is append-only. The `MemoryIndex.append()` method is
idempotent on `trace_id` (it checks for duplicates before writing).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from redthread.config.settings import RedThreadSettings
from redthread.core.defense_synthesis import DeploymentRecord

logger = logging.getLogger(__name__)

_MEMORY_FILENAME = "MEMORY.md"

_ENTRY_TEMPLATE = """\
## {timestamp} | {category} | {severity}
**Trace:** `{trace_id}`
**Scope:** model=`{model}` | prompt_hash=`{prompt_hash}`
**Attack vector:** {attack_vector}

> **Guardrail clause:** {clause}

**OWASP ref:** {owasp_ref} | **MITRE ATLAS:** {mitre_ref}
**Validated:** {validated_str}

---

"""


class MemoryIndex:
    """Read/write interface for the MEMORY.md threat-knowledge index.

    Usage::

        index = MemoryIndex(settings)
        index.append(deployment_record)
        entries = index.all_entries_raw()
    """

    def __init__(self, settings: RedThreadSettings) -> None:
        self._path: Path = settings.memory_dir / _MEMORY_FILENAME
        self._ensure_header()

    # ── Public API ────────────────────────────────────────────────────────────

    def append(self, record: DeploymentRecord) -> bool:
        """Append a DeploymentRecord to the index.

        Returns:
            True  — entry written.
            False — duplicate detected, skipped.
        """
        if self._is_duplicate(record.trace_id):
            logger.debug(
                "MemoryIndex: duplicate trace_id=%s — skipping.", record.trace_id
            )
            return False

        entry = self._format_entry(record)
        with self._path.open("a", encoding="utf-8") as f:
            f.write(entry)

        logger.info(
            "📚 MemoryIndex updated | trace=%s | category=%s",
            record.trace_id,
            record.classification.category,
        )
        return True

    def all_entries_raw(self) -> str:
        """Return the full raw MEMORY.md content."""
        if not self._path.exists():
            return ""
        return self._path.read_text(encoding="utf-8")

    def known_trace_ids(self) -> list[str]:
        """Return all trace IDs already indexed."""
        raw = self.all_entries_raw()
        ids: list[str] = []
        for line in raw.splitlines():
            if line.startswith("**Trace:**"):
                # Format: **Trace:** `<trace_id>`
                trace_id = line.replace("**Trace:**", "").strip().strip("`")
                ids.append(trace_id)
        return ids

    def load_scoped_guardrails(self, target_model: str, prompt_hash: str) -> list[str]:
        """Parse MEMORY.md for all active guardrail clauses matching the scope."""
        raw = self.all_entries_raw()
        if not raw:
            return []

        clauses: list[str] = []
        blocks = raw.split("---\n\n")

        # Parse block by block. A block inherits the template structure.
        for block in blocks:
            if not block.strip():
                continue

            # We only deploy if Validated has YES
            if "✅ YES" not in block:
                continue

            # Check scope
            scope_line = f"model=`{target_model}` | prompt_hash=`{prompt_hash}`"
            if scope_line not in block:
                continue

            # Extract the guardrail clause
            # Format: > **Guardrail clause:** {clause}
            for line in block.splitlines():
                if line.startswith("> **Guardrail clause:**"):
                    clause = line.replace("> **Guardrail clause:**", "").strip()
                    clauses.append(clause)
                    break

        return clauses

    # ── Internals ─────────────────────────────────────────────────────────────

    def _ensure_header(self) -> None:
        """Create MEMORY.md with header if it doesn't exist."""
        if not self._path.exists():
            self._path.parent.mkdir(parents=True, exist_ok=True)
            header = (
                "# RedThread Threat Knowledge Base\n\n"
                "This file is auto-generated by the Defense Synthesis Engine.\n"
                "Each entry represents a confirmed jailbreak and its validated guardrail fix.\n\n"
                "---\n\n"
            )
            self._path.write_text(header, encoding="utf-8")
            logger.info("📝 Initialized MEMORY.md at %s", self._path)

    def _is_duplicate(self, trace_id: str) -> bool:
        return trace_id in self.known_trace_ids()

    def _format_entry(self, record: DeploymentRecord) -> str:
        cl = record.classification
        val = record.validation

        validated_str = (
            f"✅ YES (residual score: {val.judge_score:.2f})"
            if val.passed
            else f"❌ NO — guardrail insufficient (replay score: {val.judge_score:.2f})"
        )

        return _ENTRY_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            category=cl.category,
            severity=cl.severity,
            trace_id=record.trace_id,
            model=record.target_model,
            prompt_hash=record.target_system_prompt_hash,
            attack_vector=cl.attack_vector or "N/A",
            clause=record.guardrail_clause,
            owasp_ref=cl.owasp_ref,
            mitre_ref=cl.mitre_atlas_ref,
            validated_str=validated_str,
        )
